sudo: false
language: python
python:
  - "3.4"

cache: false

install:
  - pip install -r requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - export DJANGO_SETTINGS_MODuLE=demo.settings

addons:
  sonarqube:
    token:
      secure: $SONAR_TOKEN
  branches:
    - master

script:
  - django-admin test
  - sonar-scanner

notifications:
  email: false

branches:
  only:
    - master
